language: node_js
node_js:
  - 6
  - 8
  - 10
  - 12
sudo: false
before_install:
  - export "PATH=./node_modules/.bin:$PATH"
install: npm install
script:
  - gulp lint
  - gulp dist
  - gulp test karma
after_success:
  - gulp coveralls

